# Generated by Django 5.0.2 on 2024-03-30 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0001_initial"),
        ("product", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("type", models.TextField(max_length=50)),
                ("amount", models.PositiveIntegerField(default=0)),
                ("free_shipping", models.BooleanField(default=False)),
                ("expired_at", models.DateField()),
                ("minimum", models.PositiveIntegerField(default=0)),
                ("maximum", models.PositiveIntegerField(default=0)),
                ("individual_use", models.BooleanField(default=False)),
                ("exclude_sale_items", models.BooleanField(default=False)),
                ("usage_limit", models.IntegerField(default=0)),
                ("item_limit", models.IntegerField(default=0)),
                ("user_limit", models.IntegerField(default=0)),
                (
                    "allowed_users",
                    models.ManyToManyField(
                        blank=True, related_name="coupons", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="coupons", to="category.category"
                    ),
                ),
                (
                    "exclude_categories",
                    models.ManyToManyField(blank=True, to="category.category"),
                ),
                (
                    "exclude_products",
                    models.ManyToManyField(blank=True, to="product.product"),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="coupons", to="product.product"
                    ),
                ),
                (
                    "user_used",
                    models.ManyToManyField(
                        blank=True,
                        related_name="coupons_used",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
