# Generated by Django 5.0.2 on 2024-03-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="item_limit",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="usage_limit",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="user_limit",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
