# Generated by Django 5.0.2 on 2024-03-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0002_alter_coupon_item_limit_alter_coupon_usage_limit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="maximum",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="minimum",
            field=models.IntegerField(default=0),
        ),
    ]
