# Generated by Django 5.0.2 on 2024-08-05 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attribute', '0001_initial'),
        ('category', '0001_initial'),
        ('shipping', '0001_initial'),
        ('tax', '0001_initial'),
        ('value', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, default=None, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('type', models.CharField(choices=[('simple', 'simple'), ('variation', 'variation'), ('variant', 'variant')], max_length=50)),
                ('backorder', models.CharField(choices=[('allow', 'allow'), ('notify', 'notify'), ('not_allow', 'not_allow')], default='not_allow', max_length=50)),
                ('regular_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('tax_status', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=50)),
                ('mpn', models.CharField(max_length=50)),
                ('stock_management', models.BooleanField(default=False)),
                ('stock_status', models.CharField(choices=[('in_stock', 'in_stock'), ('out_of_stock', 'out_of_stock'), ('on_backorder', 'on_backorder')], default='in_stock', max_length=50)),
                ('sold_individually', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, default=0, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('weight', models.IntegerField(default=0)),
                ('length', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('categories', models.ManyToManyField(related_name='products', to='category.category')),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='product.product')),
                ('shipping_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.shipping')),
                ('tax_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tax.tax')),
                ('values', models.ManyToManyField(related_name='products', to='value.value')),
            ],
            options={
                'ordering': ['stock'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=False)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='attribute.attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product.product')),
            ],
        ),
    ]
