# Generated by Django 5.0.2 on 2024-08-05 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(max_length=63)),
                ('states', models.TextField(max_length=63)),
                ('zip_code', models.TextField(max_length=63)),
                ('name', models.TextField(max_length=63)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('on_shipping', models.BooleanField(default=True)),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='tax.tax')),
            ],
        ),
    ]
