# Generated by Django 5.0.2 on 2024-08-05 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('free_shipping', 'free_shipping'), ('flat_rate', 'flat_rate'), ('local_pickup', 'local_pickup')], max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('free_shipping_requirements', models.CharField(blank=True, choices=[('none', 'none'), ('coupon', 'coupon'), ('minimum', 'minimum'), ('minimum_or_coupon', 'minimum_or_coupon'), ('minimum_and_coupon', 'minimum_and_coupon')], max_length=50, null=True)),
                ('minimum_order_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('flate_rate_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('local_pickup_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('taxable', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('shipping_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.shipping')),
                ('shipping_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='shipping.method')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('wildcard', models.TextField(blank=True, max_length=255, null=True)),
                ('regions', models.ManyToManyField(blank=True, to='base.region')),
            ],
        ),
        migrations.AddField(
            model_name='method',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='shipping.zone'),
        ),
    ]
