# Generated by Django 5.0.2 on 2024-08-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='flate_rate_qty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='method',
            name='local_pickup_qty',
            field=models.BooleanField(default=False),
        ),
    ]
