# Generated by Django 5.0.2 on 2024-08-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_method_flate_rate_qty_method_local_pickup_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='cost_qty',
            field=models.BooleanField(default=False),
        ),
    ]
