# Generated by Django 5.0.2 on 2024-08-08 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_basket_discounted_price_order_discounted_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='total',
        ),
    ]
