# Generated by Django 5.0.2 on 2024-08-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_price_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='subtotal',
        ),
    ]
