# Generated by Django 5.0.2 on 2024-08-08 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_rename_total_order_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='post_code',
            new_name='postcode',
        ),
    ]
